### ISSUE TITLE
Heures creuses jamais prises en compte

### ISSUE THREAD

**Issue by Nardol** [saniho/apiEnedis#66]
Hello,

Malgré la config forcée dans le fichier sensors.yaml, j'ai toujours 0 en consommation heures creuses.
Je lis régulièrement que c'est corrigé chez tout le monde mais c'est à croire que j'ai un souci que les autres n'ont pas :)

Ma config :
```yaml
- platform: myEnedis
  token: !secret enedis_token
  code: !secret enedis_pdl
  hc_cout: 0.1353
  hp_cout: 0.1853
  heures_creuses: "[['00:00', '06:36'], ['22:36', '24:00']]"
  heuresCreusesON: true
  scan_interval: 3600
```

J'ai peut-être loupé quelque chose mais il me semble pourtant avoir tout configuré.

J'utilise la vue Lovelace par défaut, en mode anarchie d'entitée (pas le choix).
Par les outils de développement, `sensor.myenedis_xxx` semble bien avoir des données en hc, par contre `myenedis_xxx_hc` est à 0.
